Update version-bump.yml

diff --git a/.github/workflows/version-bump.yml b/.github/workflows/version-bump.yml
--- a/.github/workflows/version-bump.yml
+++ b/.github/workflows/version-bump.yml
@@ -22,15 +22,17 @@ jobs:
       
     - name: Determine new version
       run: >-
-        version=$(grep -Po '[0-9]+\.[0-9]+\.[0-9]+' build.gradle.kts) IFS='.' read -r -a array <<< "$version"
+        version=$(grep -Po '[0-9]+\.[0-9]+\.[0-9]+' build.gradle.kts)
+        IFS='.' read -r -a array <<< "$version"
         echo "Previous version: $version"
-        case "${{ github.event.inputs.version_type }}" in
-          "major") new_version="$((array[0]+1)).0.0" ;;
-          "minor") new_version="${array[0]}.$((array[1]+1)).0" ;;
-          "patch") new_version="${array[0]}.${array[1]}.$((array[2]+1))" ;;
-          *) echo "Invalid version type" && exit 1 ;;
+        case "$patch" in
+        "major") new_version="$((array[0]+1)).0.0" ;;
+        "minor") new_version="${array[0]}.$((array[1]+1)).0" ;;
+        "patch") new_version="${array[0]}.${array[1]}.$((array[2]+1))" ;;
+        *) echo "Invalid version type" && exit 1 ;;
         esac
         echo "New version: $new_version"
+
       
     - name: Update version
       run: sed -i "s/version = \".*\"/version = \"$new_version\"/" build.gradle.kts
